### ISSUE TITLE
拍照后，关闭红色的X会崩溃退出

### ISSUE THREAD

**Issue by blanko0o** [wildma/IDCardCamera#15]
java.lang.RuntimeException: startPreview failed
        at android.hardware.Camera.startPreview(Native Method)
        at com.rytad.widget.idCardCamera.camera.CameraPreview.startPreview(CameraPreview.java:232)
        at com.rytad.widget.idCardCamera.camera.CameraActivity.onClick(CameraActivity.java:197)
        at android.view.View.performClick(View.java:5642)
        at android.view.View$PerformClick.run(View.java:22485)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by wildma** [comment]
demo 没发现这个问题。
