### ISSUE TITLE
启动时崩溃    不可见时已经release了横竖屏 

### ISSUE THREAD

**Issue by tytreal** [wildma/IDCardCamera#16]

**Comment by wildma** [comment]
哥们，没看懂你的描述呀~

**Comment by tytreal** [comment]
> 哥们，没看懂你的描述呀~

调用的时候就报这个错
2019-07-19 17:08:31.503 1763-1763/? E/TimeWallPaper: 不可见时已经release了横竖屏 
2019-07-19 17:08:31.509 22524-22524/com.xssE/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xss, PID: 22524
    java.lang.NoSuchFieldError: No static field camera_preview of type I in class Lcom/wildma/idcardcamera/R$id; or its superclasses (declaration of 'com.wildma.idcardcamera.R$id' appears in /data/app/com.xss.xishuashua-0bwfCZTY9o0J3hcu-UYhTQ==/split_lib_slice_1_apk.apk)
        at com.wildma.idcardcamera.camera.CameraActivity.initView(CameraActivity.java:108)
        at com.wildma.idcardcamera.camera.CameraActivity.init(CameraActivity.java:103)
        at com.wildma.idcardcamera.camera.CameraActivity.onCreate(CameraActivity.java:63)
        at android.app.Activity.performCreate(Activity.java:7436)
        at android.app.Activity.performCreate(Activity.java:7426)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by wildma** [comment]
demo 没发现这个问题，请提供下手机型号、Android 版本号等信息，并描述下复现步骤。
