### ISSUE TITLE
华为 nova 3e，打开拍照界面，黑屏+闪退

### ISSUE THREAD

**Issue by yueye410** [wildma/IDCardCamera#31]
java.lang.RuntimeException: Camera is being used after Camera.release() was called
    at android.hardware.Camera.setHasPreviewCallback(Native Method)
    at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:967)
    at com.wildma.idcardcamera.camera.CameraActivity.d(CameraActivity.java:201)
    at com.wildma.idcardcamera.camera.CameraActivity.onClick(CameraActivity.java:176)
    at android.view.View.performClick(View.java:6659)
    at android.view.View.performClickInternal(View.java:6631)
    at android.view.View.access$3100(View.java:790)
    at android.view.View$PerformClick.run(View.java:26187)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by DevYJQ** [comment]
三星Note 20 也会出现这个问题

**Comment by deboLing** [comment]
vivo也出现，Camera is being used after Camera.release() was called

**Comment by kimiangel** [comment]
该怎么解决？
